services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/html/:/var/www/html/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/letsencrypt:/etc/letsencrypt  
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
       dmz:
        ipv4_address: 10.0.0.2
  php:
    build: ./php
    volumes:
      - ./nginx/html/:/var/www/html/
    depends_on:
      - mariadb
    env_file:
      - db.env
    networks:
       db_net:
         ipv4_address: 172.16.0.2
       dmz:
         ipv4_address: 10.0.0.3
  mariadb:
    image: mariadb:11.1
    restart: always
    env_file:
      - db/root.env
      - db.env
    volumes: 
      - ./db/sql/:/docker-entrypoint-initdb.d/  #MariaDB container automatically loads SQL script at startup
      - ./db/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
       db_net:
         ipv4_address: 172.16.0.3
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.l1-11.ephec-ti.be
    env_file: ./mail/mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      dmz:
        ipv4_address: 10.0.0.6

  dns:
    build: ./bind
    container_name: dns
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dmz:
        ipv4_address: 10.0.0.4

networks:
  db_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
  dmz:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

