version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passroot
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - wordpress_net
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - 8080:80
    networks:
      - wordpress_net
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: database
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
volumes:
  wordrpess_data:

networks:
  wordpress_net:


