FROM nginx:latest
	RUN apt update
RUN apt install -y nano net-tools

# Copier la configuration personnalisée de Nginx dans l'image
COPY nginx.conf /etc/nginx/nginx.conf

# Définir le répertoire racine pour les fichiers HTML
WORKDIR /var/www/html/www

# Copier les fichiers HTML dans le répertoire racine
COPY ../html/www/index.html /var/www/html/www/index.html


# Créer un répertoire pour les fichiers HTML du second site
RUN mkdir -p /var/www/html/blog

# Copier les fichiers HTML du second site
COPY ../html/www/blog-index.html /var/www/html/blog/index.html
